# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plrlctl < Formula

  head "https://github.com/pluralsh/plural-cli.git"

  test do
    system "#{bin}/plrlctl", "--help"
  end
end